# Generated by Django 5.0.4 on 2024-04-18 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('title', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('python_file', models.FileField(blank=True, null=True, upload_to='projects/files/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='portfolio_app.projectmodel')),
            ],
        ),
    ]
