# Generated by Django 5.0.4 on 2024-04-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='image',
            field=models.ImageField(upload_to='portfolio_app/media/'),
        ),
    ]
