# Generated by Django 5.0.4 on 2024-04-22 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_projectmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
