# Generated by Django 5.0.4 on 2024-04-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_projectmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
