# Generated by Django 5.0.4 on 2024-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='summary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
