# Generated by Django 5.0.4 on 2024-04-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_userprofile_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='summary',
        ),
    ]
