# Generated by Django 5.0.4 on 2024-04-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_summary_remove_userprofile_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_paragraph', models.TextField(blank=True, help_text='Enter the top paragraph of your profile description.', null=True)),
                ('paragraph_1', models.TextField(blank=True, help_text='Enter the first paragraph.', null=True)),
                ('paragraph_2', models.TextField(blank=True, help_text='Enter the second paragraph.', null=True)),
                ('paragraph_3', models.TextField(blank=True, help_text='Enter the third paragraph.', null=True)),
            ],
        ),
    ]
