# Generated by Django 5.0.4 on 2024-04-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_profiledescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_app/media/'),
        ),
    ]
