# Generated by Django 5.0.4 on 2024-04-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_profiledescription_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, help_text='Job title.', max_length=100, null=True)),
                ('company', models.CharField(blank=True, help_text='Company name.', max_length=100, null=True)),
                ('start_year', models.IntegerField(blank=True, help_text='Start year of the work period.', null=True)),
                ('end_year', models.IntegerField(blank=True, help_text='End year of the work period. Use the current year if still working.', null=True)),
            ],
        ),
    ]
